/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package majafrydrych.Client.Forms;

import majafrydrych.Client.Logic.Client;
import majafrydrych.Common.Logic.RoomData;
import majafrydrych.Events.GetRoomListListener;

import java.util.ArrayList;

/**
 *
 * @author Maja Frydrych
 */
public class RoomBrowser extends javax.swing.JFrame {
    private Client client;

    /**
     * Creates new form RoomBrowser
     */
    public RoomBrowser(Client client) {
        this.client = client;
        initComponents();
        client.setGetRoomListListener(new GetRoomListListener() {
            @Override
            public void roomsListReceived(ArrayList<RoomData> roomsList) {
                updateRoomList(roomsList);
            }
        });
    }

    private void updateRoomList(ArrayList<RoomData> roomsList) {
        String[] rooms = new String[roomsList.size()];
        if (roomsList.isEmpty()) {
            rooms = new String[1];
            rooms[0] = "Brak pokoi";
        }
        for (int i = 0; i < roomsList.size(); i++) {
            rooms[i] = "Id: " + roomsList.get(i).roomId + " - " + "players: " + roomsList.get(i).playerNumber + "/2" + " - " + "host: " + roomsList.get(i).host;
        }
        RoomList.setListData(rooms);
    }

    private RoomBrowser() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnExit = new javax.swing.JButton();
        BtnCreateRoom = new javax.swing.JButton();
        BtnRefresh = new javax.swing.JButton();
        SpRoom = new javax.swing.JScrollPane();
        RoomList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnExit.setText("Wyjdź");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        BtnCreateRoom.setText("Utwórz pokój");
        BtnCreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateRoomActionPerformed(evt);
            }
        });

        BtnRefresh.setText("Refresh");
        BtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefreshActionPerformed(evt);
            }
        });

        SpRoom.setViewportView(RoomList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 308, Short.MAX_VALUE)
                        .addComponent(BtnRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCreateRoom)
                        .addGap(18, 18, 18)
                        .addComponent(BtnExit))
                    .addComponent(SpRoom))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnExit)
                    .addComponent(BtnCreateRoom)
                    .addComponent(BtnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefreshActionPerformed
        client.requestRoomList();
    }//GEN-LAST:event_BtnRefreshActionPerformed

    private void BtnCreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateRoomActionPerformed
        client.requestCreateRoom();
    }//GEN-LAST:event_BtnCreateRoomActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        client.requestLeaveServer();
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomBrowser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreateRoom;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JList<String> RoomList;
    private javax.swing.JScrollPane SpRoom;
    // End of variables declaration//GEN-END:variables
}
