/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package majafrydrych.Server.Forms;

import java.net.InetAddress;
import majafrydrych.Common.Validation.FormValidation;
import majafrydrych.Common.DataParsing.ParseHelper;
import majafrydrych.Server.Logic.Server;

/**
 *
 * @author Maja Frydrych
 */
public class ServerConfigForm extends javax.swing.JFrame {
    
    public boolean isServerStarted = false;
    ServerStatusForm serverStatusForm = null;

    /**
     * Creates new form ServerConfigForm
     */
    public ServerConfigForm() {
        initComponents();  
    }
    
    private boolean validateServerConfig() {
        boolean validatedAddres = FormValidation.validateIPAdress(TbIPAddress.getText());
        boolean validatedPort = FormValidation.validatePort(TbPort.getText());
        return validatedAddres && validatedPort;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbIPAdress = new javax.swing.JLabel();
        LbPort = new javax.swing.JLabel();
        TbIPAddress = new javax.swing.JTextField();
        TbPort = new javax.swing.JTextField();
        BtnStartServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LbIPAdress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbIPAdress.setText("Adres IP");

        LbPort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbPort.setText("Port");

        TbIPAddress.setText("localhost");

        TbPort.setText("20049");

        BtnStartServer.setText("Start");
        BtnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(BtnStartServer)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TbIPAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(LbIPAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TbPort, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(LbPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbIPAdress)
                    .addComponent(LbPort))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TbIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TbPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(BtnStartServer)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartServerActionPerformed
        if (!isServerStarted) {
            if (validateServerConfig()) {
                isServerStarted = true;
                InetAddress serverAddress = ParseHelper.parseIPAddress(TbIPAddress.getText());
                int serverPort = Integer.parseInt(TbPort.getText());
                Server server = new Server(serverAddress, serverPort);
                Thread thread = new Thread(server);
                thread.start();
                serverStatusForm = new ServerStatusForm(serverAddress, serverPort);
                serverStatusForm.show();
                hide();
            }
        }
    }//GEN-LAST:event_BtnStartServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerConfigForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerConfigForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerConfigForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerConfigForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerConfigForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnStartServer;
    private javax.swing.JLabel LbIPAdress;
    private javax.swing.JLabel LbPort;
    private javax.swing.JTextField TbIPAddress;
    private javax.swing.JTextField TbPort;
    // End of variables declaration//GEN-END:variables
}
